/*DESCRIPTION:
1. Transformation Description:
This transformation creates an activity with the following name: Begin PO Approval















2. Required Tables:
QALS
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
QALS.EBELN
QALS.EBELP
QALS.ERSTELLER
QALS.MANDANT
QALS.NOW
QALS.PASTRTERM
QALS.PASTRZEIT
TMP_P2P_EKKO_EKPO.EBELN
TMP_P2P_EKKO_EKPO.EBELP
TMP_P2P_EKKO_EKPO.MANDT
TMP_P2P_EKKO_EKPO._CASE_KEY
USR02.BNAME
USR02.MANDT
USR02.USTYP

4. Columns used for timestamp:
QALS.PASTRTERM
QALS.PASTRZEIT

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/

INSERT INTO _CEL_P2P_ACTIVITIES(
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"_CELONIS_CHANGE_DATE")
SELECT DISTINCT 
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,'Bestellfreigabe Start' AS "ACTIVITY_DE"
	,'Approval PO Start' AS "ACTIVITY_EN"
	,CAST(WF_LOG.DATUM AS DATE) + CAST(WF_LOG.ZEIT AS TIME) AS "EVENTTIME"
	,520 AS "_SORTING"
	,WF_LOG.USER_NAME AS "USER_NAME"
	,NOW() AS "_CELONIS_CHANGE_DATE"
FROM

	TMP_P2P_EKKO_EKPO AS E 
	JOIN "Z0MM_WF_LOGGING" AS WF_LOG ON 1=1
        AND WF_LOG.BELEGNUMMER = E.EBELN
        AND WF_LOG.MANDT = E.MANDT
        WHERE WF_LOG.MESSAGE_TYPE = 'CHECKIN' AND "WF_LOG"."USER_NAME" = 'SAPMAIL'
