-- Query No: 1
    DROP TABLE IF EXISTS _CEL_AP_CASES;

-- Query No: 2
CREATE TABLE _CEL_AP_CASES AS(
SELECT DISTINCT
    B._CASE_KEY,
    B.MANDT,
    B.BUKRS,
    B.BELNR,
    B.GJAHR,
    B.BUZEI,
    B.LIFNR,
    B.WAERS,
    B.WRBTR,
    B.SKNTO,
    B.SKFBT,
    CASE
	    WHEN B.WAERS = '<%=currency%>' THEN B.WRBTR*ISNULL(TCURX.TDEC,1) 
 		WHEN TCURR_CC.UKURS < 0 THEN (B.WRBTR*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		WHEN TCURR_CC.UKURS > 0 THEN (B.WRBTR*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
    END AS "WRBTR_CONVERTED",
    CASE
	    WHEN B.WAERS = '<%=currency%>' THEN B.SKFBT*ISNULL(TCURX.TDEC,1) 
	  	WHEN TCURR_CC.UKURS < 0 THEN (B.SKFBT*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		WHEN TCURR_CC.UKURS > 0 THEN (B.SKFBT*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
    END AS "SKFBT_CONVERTED",
    CASE
	    WHEN B.WAERS = '<%=currency%>' THEN B.WSKTO*ISNULL(TCURX.TDEC,1)
 	   	WHEN TCURR_CC.UKURS < 0 THEN (B.WSKTO*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		WHEN TCURR_CC.UKURS > 0 THEN (B.WSKTO*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
    END AS "SKNTO_CONVERTED"
FROM
    TMP_AP_BKPF_BSEG AS B
    /*
    LEFT JOIN {{SOURCE_SCHEMA}}.T001 AS T001 ON 1=1
        AND B.MANDT = T001.MANDT 
        AND B.BUKRS = T001.BUKRS
    */
    LEFT JOIN TCURR_CC AS TCURR_CC ON 1=1
	    AND TCURR_CC.MANDT = B.MANDT
	    AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = B.WAERS
		AND TCURR_CC.KURST = '<%=exchangeRateType%>'
		AND B.CPUDT >= TCURR_CC.VALID_START 
		AND B.CPUDT < TCURR_CC.VALID_END
	LEFT JOIN TCURF_CC AS TCURF_CC ON 1=1
	    AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
		AND B.CPUDT >= TCURF_CC.VALID_START 
		AND B.CPUDT < TCURF_CC.VALID_END
    LEFT JOIN (
		SELECT 
		    TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
		    TCURX) AS TCURX ON 1=1
		AND TCURR_CC.FCURR = TCURX.CURRKEY
);