INSERT INTO "_CEL_AP_ACTIVITIES" (
	"_CASE_KEY",
	"ACTIVITY_DE",
	"ACTIVITY_EN",
	"EVENTTIME",
	"_SORTING"
	,"MANDT"
	,"BUKRS"
	,"BELNR"
	,"GJAHR"
	,"BUZEI")
SELECT DISTINCT
	B."_CASE_KEY"  AS "_CASE_KEY"
	,'Erreiche Zahlfrist' AS "ACTIVITY_DE"
	,'Due Date passed' AS "ACTIVITY_EN"
	,CAST( CASE
		WHEN B."ZBD3T">0 
			THEN B."ZFBDT" + B."ZBD3T" * INTERVAL '1 day'
		WHEN B."ZBD3T"=0 AND B."ZBD2T">0 
			THEN B."ZFBDT" + B."ZBD2T" * INTERVAL '1 day'
		WHEN B."ZBD3T"=0 AND B."ZBD2T"=0 AND B."ZBD1T">0 
			THEN B."ZFBDT" + B."ZBD1T" * INTERVAL '1 day'
		ELSE 
		    B."ZFBDT"
       	END AS DATE) + CAST('23:59:59' AS TIME)
	AS "EVENTTIME"
	,140 AS "_SORTING"
	,B."MANDT" AS "MANDT"
	,B."BUKRS" AS "BUKRS"
	,B."BELNR" AS "BELNR"
	,B."GJAHR" AS "GJAHR"
	,B."BUZEI" AS "BUZEI"
FROM 
    "TMP_AP_BKPF_BSEG" AS B
;