DROP VIEW IF EXISTS "AP_LFA1";

CREATE VIEW "AP_LFA1" AS
SELECT DISTINCT 
"LFA1".*
FROM
    "LFA1" AS LFA1
    INNER JOIN "_CEL_AP_CASES" AS CASES ON 1=1
        AND CASES."MANDT" = LFA1."MANDT"
        AND CASES."LIFNR" = LFA1."LIFNR";