DELETE FROM
    "_CEL_AP_ACTIVITIES"
WHERE
    "EVENTTIME" IS NULL
;



DELETE FROM
    "_CEL_AP_ACTIVITIES"
WHERE
    YEAR("EVENTTIME") < '1900'
;


--Select COUNT(EVENTTIME) FROM "_CEL_AP_ACTIVITIES" WHERE YEAR("EVENTTIME") < '1900'




DELETE FROM
    _CEL_AP_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 -- ########## temporary fix ###########
;


DELETE FROM
    "_CEL_AP_ACTIVITIES"
WHERE
    "ACTIVITY_EN" IS NULL AND
    "ACTIVITY_DE" IS NULL
;

DROP TABLE IF EXISTS "TMP_AP_BKPF_BSEG";


UPDATE _CEL_AP_ACTIVITIES SET _CELONIS_CHANGE_DATE = NOW();