INSERT INTO "_CEL_AP_ACTIVITIES" (
    "_CASE_KEY"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"_SORTING"
	,"CHANGED_TABLE"
    ,"CHANGED_FIELD"
    ,"CHANGED_FROM"
    ,"CHANGED_TO"
    ,"CHANGE_NUMBER"
    ,"TRANSACTION_CODE"
    ,"MANDT"
	,"BUKRS"
	,"BELNR"
	,"GJAHR"
	,"BUZEI")

SELECT DISTINCT
	B."_CASE_KEY" AS "_CASE_KEY"
	,CASE
		WHEN CDPOS."FNAME" = 'ZLSCH' THEN 'Ändere Zahlweg'
		WHEN CDPOS."FNAME" = 'ZTERM' THEN 'Ändere Zahlungsbedingung'
		WHEN CDPOS."FNAME" = 'ZFBDT' THEN 'Ändere Zahlfristbasisdatum'
		WHEN CDPOS."FNAME" = 'ZBD1T' THEN 'Ändere Zahltage 1'
		WHEN CDPOS."FNAME" = 'SGTXT' THEN 'Ändere Positionstext'	
		WHEN CDPOS."FNAME" = 'ZFBDT' THEN 'Ändere Zahlfristbasisdatum'	
		WHEN CDPOS."FNAME" = 'MANSP' THEN 'Ändere Mahnsperre'
		WHEN CDPOS."FNAME" = 'ZLSPR' AND CDPOS."VALUE_OLD" IN ('R', 'A', 'S', 'I', 'M', 'D', 'Z', 'W', 'V', 'B') THEN 'Entferne Zahlsperre' 
		WHEN CDPOS."FNAME" = 'ZLSPR' AND CDPOS."VALUE_NEW" IN ('A', 'I', 'R', 'M', 'S', 'W', 'Z', 'D', 'V', 'X', 'B') THEN 'Setze Zahlsperre' 
	END AS "ACTIVITY_DE"	
	,CASE
		WHEN CDPOS."FNAME" = 'ZLSCH' THEN 'Change Payment Method'
		WHEN CDPOS."FNAME" = 'ZTERM' THEN 'Change Payment Term'
		WHEN CDPOS."FNAME" = 'ZFBDT' THEN 'Change Baseline Date'
		WHEN CDPOS."FNAME" = 'ZBD1T' THEN 'Change Payment Days 1'
		WHEN CDPOS."FNAME" = 'SGTXT' THEN 'Change Item Text'
		WHEN CDPOS."FNAME" = 'ZFBDT' THEN 'Change Baseline Date'
		WHEN CDPOS."FNAME" = 'MANSP' THEN 'Change Dunning Block'
		WHEN CDPOS."FNAME" = 'ZLSPR' AND CDPOS."VALUE_OLD" IN ('R', 'A', 'S', 'I', 'M', 'D', 'Z', 'W', 'V', 'B') THEN 'Remove Payment Block' 
		WHEN CDPOS."FNAME" = 'ZLSPR' AND CDPOS."VALUE_NEW" IN ('A', 'I', 'R', 'M', 'S', 'W', 'Z', 'D', 'V', 'X', 'B') THEN 'Set Payment Block' 
	END AS "ACTIVITY_EN"
	,CAST(CDHDR."UDATE" AS DATE) + CAST(CDHDR."UTIME" AS TIME) AS "EVENTTIME"
	,CDHDR."USERNAME" AS "USER_NAME"
	,USR02."USTYP" AS "USER_TYPE"
	,CASE
		WHEN CDPOS."FNAME" = 'ZLSCH' THEN 30
		WHEN CDPOS."FNAME" = 'ZTERM' THEN 40
		WHEN CDPOS."FNAME" = 'ZFBDT' THEN 50
		WHEN CDPOS."FNAME" = 'ZBD1T' THEN 60
		WHEN CDPOS."FNAME" = 'SGTXT' THEN 70
		WHEN CDPOS."FNAME" = 'ZFBDT' THEN 80
		WHEN CDPOS."FNAME" = 'MANSP' THEN 90
		WHEN CDPOS."FNAME"  = 'ZLSPR' AND CDPOS."VALUE_NEW" IS NULL THEN 100
		WHEN CDPOS."FNAME" = 'ZLSPR' AND CDPOS."VALUE_OLD" IS NULL THEN 110
	END AS "_SORTING"
	,CDPOS."TABNAME" AS "CHANGED_TABLE"
	,CDPOS."FNAME" AS "CHANGED_FIELD"
	,CDPOS."VALUE_OLD" AS "CHANGED_FROM"
	,CDPOS."VALUE_NEW" AS "CHANGED_TO"
	,CDPOS."CHANGENR" AS "CHANGE_NUMBER"
	,CDHDR."TCODE" AS "TRANSACTION_CODE"
	,B."MANDT" AS "MANDT"
	,B."BUKRS" AS "BUKRS"
	,B."BELNR" AS "BELNR"
	,B."GJAHR" AS "GJAHR"
	,B."BUZEI" AS "BUZEI"
FROM 
    "TMP_AP_BKPF_BSEG" AS B
	INNER JOIN "CDPOS" AS CDPOS ON 1=1
	    AND CDPOS."MANDANT" = B."MANDT"
		AND CDPOS."TABKEY" = B."_CASE_KEY"
	INNER JOIN "CDHDR" as CDHDR ON 1=1
		AND CDHDR."MANDANT" = CDPOS."MANDANT"
		AND CDHDR."CHANGENR" = CDPOS."CHANGENR"
	LEFT JOIN  "USR02" AS USR02 ON 1=1
		AND CDHDR."MANDANT" = USR02."MANDT"
    	AND CDHDR."USERNAME" = USR02."BNAME"
WHERE 1=1
    AND CDPOS."TABNAME" IN ('BSEG')
    AND CDPOS."FNAME" IN ('ZLSCH','ZTERM', 'ZBD1P', 'ZBD2P', 'ZBD1T', 'ZBD2T', 'ZBD3T','ZFBDT', 'MANSP', 'ZLSPR');


/*
    Select 
    CDPOS."TABNAME" AS "CHANGED_TABLE"
	,CDPOS."FNAME" AS "CHANGED_FIELD"
	--,CDPOS."VALUE_OLD" AS "CHANGED_FROM"
	,CDPOS."VALUE_NEW" AS "CHANGED_TO"
    ,Count(3)
    FROM CDPOS
    WHERE
    CDPOS."TABNAME" IN ('BSEG')
    AND CDPOS."FNAME" IN ('ZLSPR')
    Group by 1,2,3 Order by 4 DESC

    'R', 'A', 'S', 'I', 'M', 'D', 'Z', 'W', 'V', 'B'
    'A', 'I', 'R', 'M', 'S', 'W', 'Z', 'D', 'V', 'X', 'B'

*/