INSERT INTO "_CEL_AP_ACTIVITIES" (
	"_CASE_KEY",
	"ACTIVITY_DE",
	"ACTIVITY_EN",
	"EVENTTIME",
	"USER_NAME",
	"USER_TYPE",
	"_SORTING"
	,"MANDT"
	,"BUKRS"
	,"BELNR"
	,"GJAHR"
	,"BUZEI"
    ,"TRANSACTION_CODE"
)
SELECT DISTINCT
--<Required Fields for the Process
    B."_CASE_KEY"  AS "_CASE_KEY"
	,'Gleiche Rechnung aus' AS "ACTIVITY_DE"
	,'Clear Invoice' AS "ACTIVITY_EN"
  	,CASE 
  		WHEN CAST(BKPF_Z."CPUDT" AS DATE) = CAST(B."AUGDT" AS DATE)
  		THEN CAST(BKPF_Z."CPUDT" AS DATE) + CAST(BKPF_Z."CPUTM" as TIME)
  		ELSE CAST(B."AUGDT" AS DATE) + CAST('23:59:59' as TIME)
  	END AS "EVENTTIME"
	,BKPF_Z."USNAM" AS "USER_NAME"
	,USR02."USTYP" AS "USER_TYPE"
	,120 AS "_SORTING"
	,B."MANDT" AS "MANDT"
	,B."BUKRS" AS "BUKRS"
	,B."BELNR" AS "BELNR"
	,B."GJAHR" AS "GJAHR"
	,B."BUZEI" AS "BUZEI"
    ,BKPF_Z."TCODE" AS "TRANSACTION_CODE"
FROM 
    "TMP_AP_BKPF_BSEG" AS B
	LEFT JOIN "BKPF"  AS BKPF_Z ON 1=1
		AND B."MANDT" = BKPF_Z."MANDT"
		AND B."BUKRS" = BKPF_Z."BUKRS"
		AND B."AUGBL" = BKPF_Z."BELNR"
 	 	AND B."AUGGJ" = BKPF_Z."GJAHR"
	LEFT JOIN "USR02" AS USR02 ON 1=1
		AND BKPF_Z."MANDT" = USR02."MANDT"
		AND BKPF_Z."USNAM" = USR02."BNAME"
        AND B.XREVERSAL NOT IN ('1','2')
;