INSERT INTO "_CEL_AP_ACTIVITIES" (
	"_CASE_KEY",
	"ACTIVITY_DE",
	"ACTIVITY_EN",
	"EVENTTIME",
	"_SORTING"
	,"MANDT"
	,"BUKRS" 		
	,"BELNR"
	,"GJAHR"
	,"BUZEI")
SELECT DISTINCT
    B."_CASE_KEY"  AS "_CASE_KEY"
	,'Erreiche Skontofrist' AS "ACTIVITY_DE"
	,'Cash Discount Due Date passed' AS "ACTIVITY_EN"
	,CAST((B."ZFBDT" + B."ZBD1T" * INTERVAL '1 day') AS DATE) + CAST('23:59:59' AS TIME) AS "EVENTTIME" 
	,130 AS "_SORTING"
	,B."MANDT" AS "MANDT"
	,B."BUKRS" AS "BUKRS"
	,B."BELNR" AS "BELNR"
	,B."GJAHR" AS "GJAHR"
	,B."BUZEI" AS "BUZEI"
FROM 
	"TMP_AP_BKPF_BSEG" AS B
WHERE 1=1
	AND B."ZBD1P" > 0;