DROP VIEW IF EXISTS "AP_LFB1";

CREATE VIEW "AP_LFB1" AS
SELECT DISTINCT 
"LFB1".*,
    CAST(CERDT AS DATE) AS TS_CERDT, 
    CAST(DATLZ AS DATE) AS TS_DATLZ, 
    CAST(ERDAT AS DATE) AS TS_ERDAT, 
    CAST(QSZDT AS DATE) AS TS_QSZDT, 
    CAST(UPDAT AS DATE) AS TS_UPDAT, 
    CAST(ZINDT AS DATE) AS TS_ZINDT
FROM
    "LFB1" AS LFB1
    INNER JOIN "_CEL_AP_CASES" AS CASES ON 1=1
        AND CASES."MANDT" = LFB1."MANDT"
        AND CASES."LIFNR" = LFB1."LIFNR"
        AND CASES."BUKRS" = LFB1."BUKRS";