INSERT INTO "_CEL_AP_ACTIVITIES" (
    "_CASE_KEY"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"_SORTING"
    ,"MANDT"
	,"BUKRS"
	,"BELNR"
	,"GJAHR"
	,"BUZEI"
    ,"TRANSACTION_CODE")
SELECT DISTINCT
  	B."_CASE_KEY" AS "_CASE_KEY"
  	,'Erfasse im SAP' AS "ACTIVITY_DE"
  	,'Enter in SAP' AS "ACTIVITY_EN"
  	,CAST(B."CPUDT" AS DATE) + CAST(B."CPUTM" AS TIME) AS "EVENTTIME"
  	,B."USNAM" AS "USER_NAME"
  	,USR02."USTYP" AS "USER_TYPE"
  	,20 AS "_SORTING"
  	,B."MANDT" AS "MANDT"
	,B."BUKRS" AS "BUKRS"
	,B."BELNR" AS "BELNR"
	,B."GJAHR" AS "GJAHR"
	,B."BUZEI" AS "BUZEI"
    ,B."TCODE" AS "TRANSACTION_CODE"
FROM
  	"TMP_AP_BKPF_BSEG" AS B
  	LEFT JOIN "USR02" AS USR02 ON 1=1
  		AND B."MANDT" = USR02."MANDT"
  		AND B."USNAM" = USR02."BNAME";