DROP VIEW IF EXISTS "AP_BKPF";

CREATE VIEW "AP_BKPF" AS 
SELECT DISTINCT 
"BKPF".*, 
    CAST(BKPF.BLDAT AS DATE) AS TS_BLDAT, 
    CAST(BKPF.BUDAT AS DATE) AS TS_BUDAT, 
    CAST(BKPF.CPUDT AS DATE) AS TS_CPUDT, 
    CAST(BKPF.AEDAT AS DATE) AS TS_AEDAT, 
    CAST(BKPF.UPDDT AS DATE) AS TS_UPDDT, 
    CAST(BKPF.WWERT AS DATE) AS TS_WWERT, 
    CAST(BKPF.STODT AS DATE) AS TS_STODT, 
    CAST(BKPF.REINDAT AS DATE) AS TS_REINDAT, 
    CAST(BKPF.VATDATE AS DATE) AS TS_VATDATE, 
    CAST(BKPF.INTDATE AS DATE) AS TS_INTDATE, 
    CAST(BKPF.PSOBT AS DATE) AS TS_PSOBT, 
    CAST(BKPF.PSODT AS DATE) AS TS_PSODT, 
    CAST(BKPF.OFFSET_REFER_DAT AS DATE) AS TS_OFFSET_REFER_DAT, 
   --COALESCE(T003T."LTEXT",'') AS "BLART_TEXT",
    COALESCE(T001."BUTXT",'') AS "BUKRS_TEXT"
FROM    
    "BKPF" AS BKPF
    INNER JOIN "_CEL_AP_CASES" AS CASES ON 1=1
        AND CASES."MANDT" = BKPF."MANDT"
        AND CASES."BUKRS" = BKPF."BUKRS"
        AND CASES."BELNR" = BKPF."BELNR"
        AND CASES."GJAHR" = BKPF."GJAHR"
    --LEFT JOIN "T003T" AS T003T ON 1=1
    --    AND BKPF."MANDT" = T003T."MANDT"
    --    AND BKPF."BLART" = T003T."BLART"
    --    AND T003T."SPRAS" = '<%=primaryLanguageKey%>'
    LEFT JOIN "T001" AS T001 ON 1=1
        AND BKPF."MANDT" = T001."MANDT"
        AND BKPF."BUKRS" = T001."BUKRS"
        AND T001."SPRAS" = '<%=primaryLanguageKey%>';