DROP VIEW IF EXISTS "AP_BSEG";

CREATE VIEW "AP_BSEG" AS (
SELECT DISTINCT 
"BSEG".*, 
    CAST(BSEG.ZBD1T AS INTEGER) AS ZBD1T_INT,
    CAST(BSEG.AUGDT AS DATE) AS TS_AUGDT, 
    CAST(BSEG.AUGCP AS DATE) AS TS_AUGCP, 
    CAST(BSEG.VALUT AS DATE) AS TS_VALUT, 
    CAST(BSEG.FDTAG AS DATE) AS TS_FDTAG, 
    CAST(BSEG.BZDAT AS DATE) AS TS_BZDAT, 
    CAST(BSEG.ZFBDT AS DATE) AS TS_ZFBDT, 
    CAST(BSEG.ZOLLD AS DATE) AS TS_ZOLLD, 
    CAST(BSEG.VRSDT AS DATE) AS TS_VRSDT, 
    CAST(BSEG.ANFAE AS DATE) AS TS_ANFAE, 
    CAST(BSEG.MADAT AS DATE) AS TS_MADAT, 
    CAST(BSEG.DABRZ AS DATE) AS TS_DABRZ, 
    CAST(BSEG.LINFV AS DATE) AS TS_LINFV, 
    CAST(BSEG.TXDAT AS DATE) AS TS_TXDAT, 
    CAST(BSEG.PEROP_BEG AS DATE) AS TS_PEROP_BEG, 
    CAST(BSEG.PEROP_END AS DATE) AS TS_PEROP_END, 
    CAST(BSEG.PRODPER AS DATE) AS TS_PRODPER,
    --COALESCE(TBSLT."LTEXT",'') AS "BSCHL_TEXT",
    COALESCE(T001."BUTXT",'') AS "BUKRS_TEXT",
    CASES."WRBTR_CONVERTED" AS "WRBTR_CONVERTED",
    CASES."SKFBT_CONVERTED" AS "SKFBT_CONVERTED",
    CASES."SKNTO_CONVERTED" AS "SKNTO_CONVERTED"
FROM 
    "BSEG" AS BSEG
    INNER JOIN "_CEL_AP_CASES" AS CASES ON 1=1
        AND CASES."MANDT" = BSEG."MANDT"
        AND CASES."BUKRS" = BSEG."BUKRS"
        AND CASES."BELNR" = BSEG."BELNR"
        AND CASES."GJAHR" = BSEG."GJAHR"
        AND CASES."BUZEI" = BSEG."BUZEI"
    JOIN "BKPF" AS BKPF ON 1=1
        AND BKPF."MANDT" = BSEG."MANDT"
        AND BKPF."BUKRS" = BSEG."BUKRS"
        AND BKPF."BELNR" = BSEG."BELNR"
        AND BKPF."GJAHR" = BSEG."GJAHR"
    --LEFT JOIN "TBSLT" AS TBSLT ON 1=1
    --    AND BSEG."MANDT" = TBSLT."MANDT"
    --    AND BSEG."BSCHL" = TBSLT."BSCHL"
    --    AND TBSLT."SPRAS" = '<%=primaryLanguageKey%>'
    LEFT JOIN "T001" AS T001 ON 1=1
        AND BSEG."MANDT" = T001."MANDT"
        AND BSEG."BUKRS" = T001."BUKRS"
);