DROP TABLE IF EXISTS "_CEL_AP_ACTIVITIES";
-- Query No: 3
CREATE TABLE "_CEL_AP_ACTIVITIES" (
	"_CASE_KEY" VARCHAR(30)
	,"ACTIVITY_DE" VARCHAR(60)
	,"ACTIVITY_EN" VARCHAR(60)
	,"EVENTTIME" DATETIME
	,"_SORTING" INTEGER
	,"USER_NAME" VARCHAR(100)
	,"USER_TYPE" VARCHAR(30) 
	,"CHANGED_TABLE" VARCHAR(20)
    ,"CHANGED_FIELD" VARCHAR(20)
    ,"CHANGED_FROM" VARCHAR (50)
    ,"CHANGED_TO" VARCHAR(50)
    ,"CHANGED_FROM_FLOAT" FLOAT
    ,"CHANGED_TO_FLOAT" FLOAT
    ,"CHANGE_NUMBER" VARCHAR(50)
    ,"TRANSACTION_CODE" VARCHAR(20)
	,"MANDT" VARCHAR(10)
	,"BUKRS" VARCHAR(4)
	,"BELNR" VARCHAR(10)
	,"GJAHR" VARCHAR(10)
	,"BUZEI" VARCHAR(10)
    ,"_CELONIS_CHANGE_DATE" DATETIME
);