INSERT INTO _CEL_P2P_ACTIVITIES(
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"_CELONIS_CHANGE_DATE")
SELECT DISTINCT 
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,'Rechnungseingang EASY' AS "ACTIVITY_DE"
	,'Invoice Receipt EASY' AS "ACTIVITY_EN"
	,to_timestamp(IFIVH.ENTRY, 'YYYYMMDDHH24MISS') AS "EVENTTIME"
	,2310 AS "_SORTING"
	,IFIVH."SCANUSER" AS "USER_NAME"
	,NOW() AS "_CELONIS_CHANGE_DATE"
from  TMP_P2P_EKKO_EKPO AS E 
inner join "/WMD/FP_IVPO" as P on 1 = 1
        AND P.MANDT = E.MANDT
        AND P.EBELN = E.EBELN
        AND P.EBELP = E.EBELP
INNER JOIN "/WMD/FP_IVHD" AS H ON 1=1
    and H.MANDT = P.MANDT 
    and H."RECNO" = P.RECNO
inner join "/WMD/FP_IFIVH" as IFIVH on 1 = 1
    and H.MANDT = IFIVH.MANDT 
    and H."RECNO" = IFIVH.RECNO;


/*
old 
from  RSEG AS RSEG
    INNER JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
        AND RSEG.MANDT = E.MANDT
        AND RSEG.EBELN = E.EBELN
        AND RSEG.EBELP = E.EBELP
    INNER JOIN TMP_P2P_BKPF_BSEG AS B ON 1=1
        AND B.MANDT = RSEG.MANDT
        AND SUBSTRING(B.AWKEY,1,14) = RSEG.BELNR || CAST(RSEG.GJAHR AS VARCHAR(4))
inner join "/WMD/FP_IVPO" as P on 1 = 1
        AND P.MANDT = E.MANDT
        AND P.EBELN = E.EBELN
        AND P.EBELP = E.EBELP
INNER JOIN "/WMD/FP_IVHD" AS H ON 1=1
        AND H.MANDT = RSEG.MANDT
        AND  RSEG.BELNR  = H."BELNR_FI"
inner join "/WMD/FP_IFIVH" as IFIVH on 1 = 1
    and H.MANDT = IFIVH.MANDT 
    and H."RECNO" = IFIVH.RECNO

*/


