/*DESCRIPTION:
1. Transformation Description:
This transformation creates the following activities: Change Contract, Receive Order Confirmation, Delete Purchase Order Item, Change Storage Location, Block Purchase Order Item, Change Delivery Indicator, Reactivate Purchase Order Item, Update Order Confirmation, Change Final Invoice Indicator, Change Outward Delivery Indicator, Change Rejection Indicator, Change Price, Change Quantity, Change Quality Evaluation, Change Deletion Flag for Purchase Order Item

















2. Required Tables:
CDHDR
CDPOS
T001
TCURF_CC
TCURR_CC
TCURX
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
CDHDR.CHANGENR
CDHDR.MANDANT
CDHDR.TCODE
CDHDR.UDATE
CDHDR.USERNAME
CDHDR.UTIME
CDPOS.CHANGENR
CDPOS.FNAME
CDPOS.MANDANT
CDPOS.OBJECTID
CDPOS.TABKEY
CDPOS.TABNAME
CDPOS.VALUE_NEW
CDPOS.VALUE_OLD
T001.BUKRS
T001.MANDT
TCURF_CC.FCURR
TCURF_CC.FFACT
TCURF_CC.KURST
TCURF_CC.MANDT
...
Contact App Store support for the complete list.

4

WARNING: DESCRIPTION TOO LONG AND WAS CUT OFF!
*/
INSERT INTO _CEL_P2P_ACTIVITIES (
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
	,"CHANGED_TABLE"
	,"CHANGED_FIELD"
	,"CHANGED_FROM"
	,"CHANGED_TO"
	,"CHANGED_FROM_FLOAT"
	,"CHANGED_TO_FLOAT"
	,"CHANGE_NUMBER"
	,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,CASE
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_NEW ='S' THEN 'Sperre Bestellposition'
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_OLD ='S' AND TRIM(CDPOS.VALUE_NEW) = '' THEN 'Reaktiviere Bestellposition'
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_NEW ='L' THEN 'Lösche Bestellposition'
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_OLD ='L' AND TRIM(CDPOS.VALUE_NEW) = '' THEN 'Reaktiviere Bestellposition'
		WHEN CDPOS.FNAME = 'LOEKZ' THEN 'Ändere Löschkennzeichen für Bestellposition'
		WHEN CDPOS.FNAME = 'NETPR' THEN 'Ändere Preis'
		WHEN CDPOS.FNAME = 'MENGE' THEN 'Ändere Menge'
		WHEN CDPOS.FNAME = 'LGORT' THEN 'Ändere Lagerort'
		WHEN CDPOS.FNAME = 'LABNR' AND TRIM(CDPOS.VALUE_OLD) = '' THEN 'Erhalte Auftragsbestätigung'
		WHEN CDPOS.FNAME = 'LABNR' THEN 'Ändere Auftragsbestätigung'
		WHEN CDPOS.FNAME = 'ELIKZ' THEN 'Ändere Endlieferungskennzeichen'
		WHEN CDPOS.FNAME = 'EREKZ' THEN 'Ändere Endrechnungskennzeichen'
		WHEN CDPOS.FNAME = 'EGLKZ' THEN 'Ändere Endauslieferungskennzeichen'
		WHEN CDPOS.FNAME = 'ABSKZ' THEN 'Ändere Absagekennzeichen'
        WHEN CDPOS.FNAME = 'KONNR' THEN 'Ändere Vertrag'
		WHEN CDPOS.FNAME = 'KTPNR' THEN 'Ändere Vertrag'
        WHEN CDPOS.FNAME = 'VBEWERTUNG' THEN 'Qualitätsbewertung Ändern'
	END AS "ACTIVITY_DE"
	,CASE 
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_NEW ='S' THEN 'Block Purchase Order Item'
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_OLD ='S' AND TRIM(CDPOS.VALUE_NEW) = ''  THEN 'Reactivate Purchase Order Item'
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_NEW ='L' THEN 'Delete Purchase Order Item'
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_OLD ='L' AND TRIM(CDPOS.VALUE_NEW) = '' THEN 'Reactivate Purchase Order Item'
		WHEN CDPOS.FNAME = 'LOEKZ' THEN 'Change Deletion Flag for Purchase Order Item'
		WHEN CDPOS.FNAME = 'NETPR' THEN 'Change Price'
		WHEN CDPOS.FNAME = 'MENGE' THEN 'Change Quantity'
		WHEN CDPOS.FNAME = 'LGORT' THEN 'Change Storage Location'
		WHEN CDPOS.FNAME = 'LABNR' AND TRIM(CDPOS.VALUE_OLD) = '' THEN 'Receive Order Confirmation'
		WHEN CDPOS.FNAME = 'LABNR' THEN 'Update Order Confirmation'
		WHEN CDPOS.FNAME = 'ELIKZ' THEN 'Change Delivery Indicator'
		WHEN CDPOS.FNAME = 'EREKZ' THEN 'Change Final Invoice Indicator'
		WHEN CDPOS.FNAME = 'EGLKZ' THEN 'Change Outward Delivery Indicator'
		WHEN CDPOS.FNAME = 'ABSKZ' THEN 'Change Rejection Indicator'
        WHEN CDPOS.FNAME = 'KONNR' THEN 'Change Contract'
		WHEN CDPOS.FNAME = 'KTPNR' THEN 'Change Contract'
        WHEN CDPOS.FNAME = 'VBEWERTUNG' THEN 'Change Quality Evaluation'
	END AS "ACTIVITY_EN"
	,CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME) AS "EVENTTIME"
	,CASE 
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_NEW ='S' THEN 610
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_OLD ='S' AND TRIM(CDPOS.VALUE_NEW) ='' THEN 620
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_NEW ='L' THEN 630
		WHEN CDPOS.FNAME = 'LOEKZ' AND CDPOS.VALUE_OLD ='L' AND TRIM(CDPOS.VALUE_NEW) = '' THEN 640
		WHEN CDPOS.FNAME = 'LOEKZ' THEN 650
		WHEN CDPOS.FNAME = 'NETPR' THEN 660
		WHEN CDPOS.FNAME = 'MENGE' THEN 670
		WHEN CDPOS.FNAME = 'LGORT' THEN 680
		WHEN CDPOS.FNAME = 'LABNR' AND COALESCE(CDPOS.VALUE_OLD, '') = '' THEN 690
		WHEN CDPOS.FNAME = 'LABNR' THEN 700
		WHEN CDPOS.FNAME = 'ELIKZ' THEN 710
		WHEN CDPOS.FNAME = 'EREKZ' THEN 720
		WHEN CDPOS.FNAME = 'EGLKZ' THEN 730
		WHEN CDPOS.FNAME = 'ABSKZ' THEN 740
        WHEN CDPOS.FNAME = 'KONNR' THEN 750
		WHEN CDPOS.FNAME = 'KTPNR' THEN 760
        WHEN CDPOS.FNAME = 'VBEWERTUNG' THEN 770
	END AS "_SORTING"
	,CDHDR.USERNAME AS "USER_NAME"
	,USR02.USTYP AS "USER_TYPE"
	,CDPOS.TABNAME AS "CHANGED_TABLE"
	,CDPOS.FNAME AS "CHANGED_FIELD"
	,CDPOS.VALUE_OLD AS "CHANGED_FROM"
	,CDPOS.VALUE_NEW AS "CHANGED_TO"
	,CASE
		WHEN CDPOS.FNAME = 'NETPR' THEN
		(CASE 
			WHEN E.WAERS = '<%=currency%>' THEN CDPOS.VALUE_OLD*ISNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CDPOS.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CDPOS.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
        END)
		ELSE CAST(NULL AS FLOAT)
	END AS "CHANGED_FROM_FLOAT"
	,CASE
		WHEN CDPOS.FNAME = 'NETPR' THEN
		(CASE 
			WHEN E.WAERS = '<%=currency%>' THEN CDPOS.VALUE_NEW*ISNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CDPOS.VALUE_NEW*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CDPOS.VALUE_NEW*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		END)
		ELSE CAST(NULL AS FLOAT)
	END AS "CHANGED_TO_FLOAT"
	,CDHDR.CHANGENR AS "CHANGE_NUMBER"
	,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY"
FROM
	CDPOS AS CDPOS
	INNER JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
		AND CDPOS.OBJECTID = E.EBELN
		AND CDPOS.TABKEY = E."_CASE_KEY"
		AND CDPOS.MANDANT = E.MANDT
	JOIN CDHDR AS CDHDR ON 1=1
		AND CDPOS.MANDANT = CDHDR.MANDANT
		AND CDPOS.CHANGENR = CDHDR.CHANGENR
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND USR02.MANDT = CDHDR.MANDANT
		AND USR02.BNAME = CDHDR.USERNAME
	LEFT JOIN TCURR_CC AS TCURR_CC ON 1=1
		AND TCURR_CC.MANDT = E.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = E.WAERS
		AND TCURR_CC.KURST = '<%=exchangeRateType%>'
		AND E.AEDAT >= TCURR_CC.VALID_START 
		AND E.AEDAT < TCURR_CC.VALID_END
	LEFT JOIN TCURF_CC AS TCURF_CC ON 1=1
		AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
		AND E.AEDAT >= TCURF_CC.VALID_START	
		AND E.AEDAT < TCURF_CC.VALID_END
	LEFT JOIN T001 AS T001 ON 1=1
		AND E.MANDT = T001.MANDT
		AND E.BUKRS = T001.BUKRS
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		AND TCURR_CC.FCURR = TCURX.CURRKEY
WHERE 1=1
	AND CDPOS.TABNAME IN ('EKPO')
	AND CDPOS.FNAME IN ('LOEKZ', 'NETPR', 'MENGE', 'LABNR','LGORT','ELIKZ', 'EREKZ','EGLKZ','ABSKZ','KONNR','KTPNR','VBEWERTUNG');