/*DESCRIPTION:
1. Transformation Description:
This transformation creates a view with the following name: P2P_EKPO

















2. Required Tables:
EKKO
EKPO
MAKT
T001
T001L
T001W
T023T
T163I
T163Y
_CEL_P2P_CASES

3. Required Columns:
EKKO.EBELN
EKKO.IFNULL
EKKO.MANDT
EKPO.*
EKPO.ABDAT
EKPO.AEDAT
EKPO.AGDAT
EKPO.BUKRS
EKPO.DPDAT
EKPO.DRDAT
EKPO.EBELN
EKPO.EBELP
EKPO.EILDT
EKPO.J_1AIDATEP
EKPO.KNTTP
EKPO.LEWED
EKPO.LGORT
EKPO.MANDT
EKPO.MATKL
EKPO.MATNR
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
None

5. Parameters used in where clause:
None

6. Parameters used in joins:
primaryLanguageKey
*/
DROP VIEW IF EXISTS P2P_EKPO;

CREATE VIEW P2P_EKPO AS (
SELECT DISTINCT 
    EKPO.*,
    "EKKO"."BSART",
 	CAST(EKPO.ABDAT AS DATE) AS TS_ABDAT, 
    CAST(EKPO.AEDAT AS DATE) AS TS_AEDAT, 
    CAST(EKPO.AGDAT AS DATE) AS TS_AGDAT, 
    CAST(EKPO.DPDAT AS DATE) AS TS_DPDAT, 
    CAST(EKPO.DRDAT AS DATE) AS TS_DRDAT, 
    CAST(EKPO.EILDT AS DATE) AS TS_EILDT, 
    CAST(EKPO.J_1AIDATEP AS DATE) AS TS_J_1AIDATEP, 
    CAST(EKPO.LEWED AS DATE) AS TS_LEWED, 
    CAST(EKPO.NFABD AS DATE) AS TS_NFABD, 
    CAST(EKPO.NLABD AS DATE) AS TS_NLABD, 
    CAST(EKPO.PRDAT AS DATE) AS TS_PRDAT,
    IFNULL(T023T.WGBEZ,'') AS "MATKL_TEXT",
	IFNULL(MAKT.MAKTX,'') AS "MATNR_TEXT",
	IFNULL(T001.BUTXT,'') AS "BUKRS_TEXT",
	IFNULL(T001W.NAME1,'') AS "WERKS_TEXT",
    IFNULL(T001W.LAND1,'') AS "WERKS_COUNTRY_KEY",
	IFNULL(T001L.LGOBE,'') AS "LGORT_TEXT",
	IFNULL(PSTYP.PTEXT,'') AS "PSTYP_TEXT",
	IFNULL(T163I.KNTTX,'') AS "KNTTP_TEXT",
	CASES.NETWR_CONVERTED AS "NETWR_CONVERTED",
  	CASES.NETPR_CONVERTED AS "NETPR_CONVERTED"
  FROM 
    EKPO AS EKPO
    INNER JOIN _CEL_P2P_CASES AS CASES ON 1=1
        AND EKPO.MANDT = CASES.MANDT
        AND EKPO.EBELN = CASES.EBELN
        AND EKPO.EBELP = CASES.EBELP
    LEFT JOIN EKKO AS EKKO ON 1=1
        AND EKPO.MANDT = EKKO.MANDT
        AND EKPO.EBELN = EKKO.EBELN
	LEFT JOIN MAKT AS MAKT ON 1=1
		AND EKPO.MANDT = MAKT.MANDT
		AND EKPO.MATNR = MAKT.MATNR
		AND MAKT.SPRAS = 'D'
	LEFT JOIN T023T AS T023T ON 1=1
		AND EKPO.MANDT = T023T.MANDT
		AND EKPO.MATKL = T023T.MATKL
		AND T023T.SPRAS = '<%=primaryLanguageKey%>' 
	LEFT JOIN T001 AS T001 ON 1=1
		AND EKPO.MANDT = T001.MANDT
		AND EKPO.BUKRS = T001.BUKRS
	LEFT JOIN T001W AS T001W ON 1=1
		AND EKPO.MANDT = T001W.MANDT
		AND EKPO.WERKS = T001W.WERKS
	LEFT JOIN T001L AS T001L ON 1=1
		AND EKPO.MANDT = T001L.MANDT
		AND EKPO.WERKS = T001L.WERKS
		AND EKPO.LGORT = T001L.LGORT
	LEFT JOIN T163Y AS PSTYP ON 1=1
		AND PSTYP.MANDT = EKPO.MANDT
		AND PSTYP.PSTYP = EKPO.PSTYP
		AND PSTYP.SPRAS = '<%=primaryLanguageKey%>'
	LEFT JOIN T163I AS T163I ON 1=1
	    AND T163I.MANDT = EKPO.MANDT
		AND T163I.KNTTP = EKPO.KNTTP	 
		AND T163I.SPRAS = '<%=primaryLanguageKey%>' 
);