/*DESCRIPTION:
1. Transformation Description:
This transformation creates a view with the following name: P2P_EKKO

















2. Required Tables:
DD07T
DD07T
EKKO
T001
T024
T024E
T161T
_CEL_P2P_CASES

3. Required Columns:
DD07T.DDLANGUAGE
DD07T.DDTEXT
DD07T.DOMNAME
DD07T.DOMVALUE_L
DD07T.IFNULL
EKKO.*
EKKO.AEDAT
EKKO.ANGDT
EKKO.BEDAT
EKKO.BNDDT
EKKO.BSART
EKKO.BSTYP
EKKO.BUKRS
EKKO.BWBDT
EKKO.DPDAT
EKKO.EBELN
EKKO.EKGRP
EKKO.EKORG
EKKO.EQ_EINDT
EKKO.GWLDT
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
None

5. Parameters used in where clause:
None

6. Parameters used in joins:
primaryLanguageKey
*/
DROP VIEW IF EXISTS P2P_EKKO;

CREATE VIEW P2P_EKKO AS (
SELECT DISTINCT 
    EKKO.*,
    CAST(EKKO.AEDAT AS DATE) AS TS_AEDAT, 
    CAST(EKKO.ANGDT AS DATE) AS TS_ANGDT, 
    CAST(EKKO.BEDAT AS DATE) AS TS_BEDAT, 
    CAST(EKKO.BNDDT AS DATE) AS TS_BNDDT, 
    CAST(EKKO.BWBDT AS DATE) AS TS_BWBDT, 
    CAST(EKKO.DPDAT AS DATE) AS TS_DPDAT, 
    CAST(EKKO.EQ_EINDT AS DATE) AS TS_EQ_EINDT, 
    CAST(EKKO.GWLDT AS DATE) AS TS_GWLDT, 
    CAST(EKKO.IHRAN AS DATE) AS TS_IHRAN, 
    CAST(EKKO.KDATB AS DATE) AS TS_KDATB, 
    CAST(EKKO.KDATE AS DATE) AS TS_KDATE, 
    CAST(EKKO.RELEASE_DATE AS DATE) AS TS_RELEASE_DATE, 
	IFNULL(DD07T.DDTEXT,'') AS "BSTYP_TEXT",
	IFNULL(DD07T_EKKO_STATU.DDTEXT,'') AS "STATU_TEXT",
	IFNULL(T161T.BATXT,'') AS "BSART_TEXT",
    IFNULL(T024E.EKOTX,'') AS "EKORG_TEXT",
	IFNULL(T001.BUTXT,'') AS "BUKRS_TEXT",
    IFNULL(T001.LAND1,'') AS "BUKRS_TEXT2",
	IFNULL(T001.WAERS,'') AS "BUKRS_TEXT3",
	IFNULL(T024.EKNAM,'') AS "EKGRP_TEXT"
FROM 
    EKKO AS EKKO
    INNER JOIN _CEL_P2P_CASES AS CASES ON 1=1
        AND EKKO.MANDT = CASES.MANDT
        AND EKKO.EBELN = CASES.EBELN
	LEFT JOIN DD07T AS DD07T ON 1=1
		AND EKKO.BSTYP = DD07T.DOMVALUE_L
		AND DD07T.DOMNAME = 'BSTYP'
		AND DD07T.DDLANGUAGE = '<%=primaryLanguageKey%>'
	LEFT JOIN DD07T AS DD07T_EKKO_STATU ON 1=1
		AND EKKO.STATU = DD07T_EKKO_STATU.DOMVALUE_L
		AND DD07T_EKKO_STATU.DOMNAME = 'ESTAK' 
		AND DD07T_EKKO_STATU.DDLANGUAGE = '<%=primaryLanguageKey%>'
	LEFT JOIN T161T AS T161T ON 1=1
		AND EKKO.MANDT = T161T.MANDT
		AND EKKO.BSART = T161T.BSART 
		AND EKKO.BSTYP = T161T.BSTYP
		AND T161T.SPRAS = '<%=primaryLanguageKey%>'
	LEFT JOIN T024E AS T024E ON 1=1
		AND EKKO.MANDT = T024E.MANDT
		AND EKKO.EKORG = T024E.EKORG
	LEFT JOIN T001 AS T001 ON 1=1
		AND EKKO.MANDT = T001.MANDT
		AND EKKO.BUKRS = T001.BUKRS
	LEFT JOIN T024 AS T024 ON 1=1
		AND EKKO.MANDT = T024.MANDT
		AND EKKO.EKGRP = T024.EKGRP
);