/*DESCRIPTION:
1. Transformation Description:
This transformation creates the following activities: Refuse Purchase Requisition, Release Purchase Requisition

















2. Required Tables:
CDHDR
CDPOS
EBAN
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
CDHDR.BLOCKPRINDICATORS
CDHDR.CHANGENR
CDHDR.MANDANT
CDHDR.RELEASEPRINDICATORS
CDHDR.TCODE
CDHDR.UDATE
CDHDR.USERNAME
CDHDR.UTIME
CDPOS.CHANGENR
CDPOS.FNAME
CDPOS.MANDANT
CDPOS.OBJECTCLAS
CDPOS.TABKEY
CDPOS.TABNAME
CDPOS.VALUE_NEW
CDPOS.VALUE_OLD
EBAN.BANFN
EBAN.BNFPO
EBAN.MANDT
TMP_P2P_EKKO_EKPO.BANFN
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
CDHDR.UDATE
CDHDR.UTIME

5. Parameters used in where clause:
releasePrIndicators
blockPrIndicators

6. Parameters used in joins:
None
*/
INSERT INTO _CEL_P2P_ACTIVITIES(
    "_CASE_KEY"
    ,"MANDT"
	,"EBELN"
	,"EBELP"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"CHANGED_TABLE"
    ,"CHANGED_FIELD"
    ,"CHANGED_FROM"
    ,"CHANGED_TO"
    ,"CHANGE_NUMBER"
    ,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
    E._CASE_KEY AS "_CASE_KEY"
    ,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
    ,CASE 
        WHEN CDPOS.VALUE_NEW IN <%=blockPrIndicators%> THEN 'Lehne BANF ab'
        WHEN CDPOS.VALUE_NEW IN <%=releasePrIndicators%> THEN 'Gebe BANF frei' 
    END AS "ACTIVITY_DE"
    ,CASE 
        WHEN CDPOS.VALUE_NEW IN <%=blockPrIndicators%> THEN 'Refuse Purchase Requisition'
        WHEN CDPOS.VALUE_NEW IN <%=releasePrIndicators%>  THEN 'Release Purchase Requisition' 
    END AS "ACTIVITY_EN"
    ,CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME) AS "EVENTTIME"
    ,CASE 
		WHEN CDPOS.VALUE_NEW IN <%=blockPrIndicators%> THEN 300
        WHEN CDPOS.VALUE_NEW IN <%=releasePrIndicators%> THEN 400	
	END AS "_SORTING"
    ,CDHDR.USERNAME AS "USER_NAME"
    ,USR02.USTYP AS "USER_TYPE"
    ,CDPOS.TABNAME AS "CHANGED_TABLE"
    ,CDPOS.FNAME AS "CHANGED_FIELD"
    ,CDPOS.VALUE_OLD AS "CHANGED_FROM"
    ,CDPOS.VALUE_NEW AS "CHANGED_TO"
    ,CDPOS.CHANGENR AS "CHANGE_NUMBER"
    ,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY"
FROM 
    TMP_P2P_EKKO_EKPO AS E 
    JOIN CDPOS AS CDPOS ON
        CDPOS.MANDANT = E.MANDT AND
        CDPOS.TABKEY = E."TABKEY_EBAN"
    JOIN CDHDR AS CDHDR ON
        CDPOS.MANDANT = CDHDR.MANDANT AND
        CDPOS.CHANGENR = CDHDR.CHANGENR
    INNER JOIN EBAN AS EBAN ON 
        E.MANDT = EBAN.MANDT AND
        E.BANFN = EBAN.BANFN AND
        E.BNFPO = EBAN.BNFPO
    LEFT JOIN USR02 AS USR02 ON
		CDHDR.MANDANT = USR02.MANDT AND
		CDHDR.USERNAME = USR02.BNAME
WHERE 
    CDPOS.OBJECTCLAS = 'BANF' AND
    CDPOS.FNAME LIKE '%FRGKZ%' AND
    (CDPOS.VALUE_NEW IN <%=blockPrIndicators%> OR CDPOS.VALUE_NEW IN <%=releasePrIndicators%>)
;


-- SELECT "CDHDR"."UDATE", "CDHDR"."UTIME", * FROM CDPOS JOIN 
--         CDHDR AS CDHDR ON
--             CDPOS.MANDANT = CDHDR.MANDANT AND
--             CDPOS.CHANGENR = CDHDR.CHANGENR
--      WHERE "CDPOS"."TABNAME" = 'EBAN' and "CDPOS"."OBJECTCLAS" = 'BANF' and "CDPOS"."FNAME" ='FRGKZ' and "CDPOS"."TABKEY" LIKE '%12704616%'