/*DESCRIPTION:
1. Transformation Description:
This transformation creates the following activities: Quality: Rejected, Quality: Accepted















2. Required Tables:
QALS
QAVE
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
QALS.EBELN
QALS.EBELP
QALS.MANDANT
QALS.NOW
QALS.PRUEFLOS
QAVE.MANDANT
QAVE.PRUEFLOS
QAVE.VBEWERTUNG
QAVE.VDATUM
QAVE.VEZEITERF
QAVE.VNAME
TMP_P2P_EKKO_EKPO.EBELN
TMP_P2P_EKKO_EKPO.EBELP
TMP_P2P_EKKO_EKPO.MANDT
TMP_P2P_EKKO_EKPO._CASE_KEY
USR02.BNAME
USR02.MANDT
USR02.USTYP

4. Columns used for timestamp:
QAVE.VDATUM
QAVE.VEZEITERF

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/
INSERT INTO _CEL_P2P_ACTIVITIES(
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
	,"_CELONIS_CHANGE_DATE"
    ,"_ACTIVITY_KEY") 
SELECT DISTINCT 
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,CASE WHEN Q.VBEWERTUNG = 'A' THEN 'Qualität: Akzeptiert' WHEN Q.VBEWERTUNG = 'R' THEN 'Qualität: Abgelehnt' ELSE 'Qualität: Nicht bewertet' END AS "ACTIVITY_DE"
    ,CASE WHEN Q.VBEWERTUNG = 'A' THEN 'Quality: Accepted' WHEN Q.VBEWERTUNG = 'R' THEN 'Quality: Rejected' ELSE 'Quality: Not evaluated'END AS "ACTIVITY_EN"
	,CAST(Q.VDATUM AS DATE) + CAST(Q.VEZEITERF AS TIME) AS "EVENTTIME"
	,2200 AS "_SORTING"
	,Q.VNAME AS "USER_NAME"
	,USR02.USTYP AS "USER_TYPE"
	,NOW() AS "_CELONIS_CHANGE_DATE"
    ,QALS.MANDANT || QALS.PRUEFLOS AS "_ACTIVITY_KEY"
FROM
	TMP_P2P_EKKO_EKPO AS E
	JOIN QALS as QALS on 1=1
		AND QALS.EBELN = E.EBELN
		AND QALS.EBELP = E.EBELP
		AND QALS.MANDANT = E.MANDT
	JOIN QAVE as Q on 1=1 
		AND Q.MANDANT = QALS.MANDANT
		AND Q.PRUEFLOS	= QALS.PRUEFLOS
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND Q.MANDANT = USR02.MANDT
		AND Q.VNAME = USR02.BNAME;