/*DESCRIPTION:
1. Transformation Description:
This transformation creates a view with the following name: P2P_BSEG

















2. Required Tables:
BKPF
BSEG
RSEG
_CEL_P2P_CASES

3. Required Columns:
BKPF.AWKEY
BKPF.BELNR
BKPF.BUKRS
BKPF.GJAHR
BKPF.MANDT
BSEG.*
BSEG.ANFAE
BSEG.AUGCP
BSEG.AUGDT
BSEG.BELNR
BSEG.BUKRS
BSEG.BZDAT
BSEG.DABRZ
BSEG.FDTAG
BSEG.GJAHR
BSEG.KOART
BSEG.LINFV
BSEG.MADAT
BSEG.MANDT
BSEG.PEROP_BEG
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
None

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/
DROP VIEW IF EXISTS P2P_BSEG;

CREATE VIEW P2P_BSEG AS 
SELECT DISTINCT 
    BSEG.*,
    CAST(BSEG.AUGDT AS DATE) AS TS_AUGDT, 
    CAST(BSEG.AUGCP AS DATE) AS TS_AUGCP, 
    CAST(BSEG.VALUT AS DATE) AS TS_VALUT, 
    CAST(BSEG.FDTAG AS DATE) AS TS_FDTAG, 
    CAST(BSEG.BZDAT AS DATE) AS TS_BZDAT, 
    CAST(BSEG.ZFBDT AS DATE) AS TS_ZFBDT, 
    CAST(BSEG.ZOLLD AS DATE) AS TS_ZOLLD, 
    CAST(BSEG.VRSDT AS DATE) AS TS_VRSDT, 
    CAST(BSEG.ANFAE AS DATE) AS TS_ANFAE, 
    CAST(BSEG.MADAT AS DATE) AS TS_MADAT, 
    CAST(BSEG.DABRZ AS DATE) AS TS_DABRZ, 
    CAST(BSEG.LINFV AS DATE) AS TS_LINFV, 
    CAST(BSEG.TXDAT AS DATE) AS TS_TXDAT, 
    CAST(BSEG.PEROP_BEG AS DATE) AS TS_PEROP_BEG, 
    CAST(BSEG.PEROP_END AS DATE) AS TS_PEROP_END, 
    CAST(BSEG.PRODPER AS DATE) AS TS_PRODPER
FROM 
    BSEG AS BSEG
	INNER JOIN BKPF AS BKPF ON 1=1
        AND BKPF.MANDT = BSEG.MANDT
        AND BKPF.BUKRS = BSEG.BUKRS
        AND BKPF.BELNR = BSEG.BELNR
        AND BKPF.GJAHR = BSEG.GJAHR
    INNER JOIN RSEG AS RSEG ON 1=1
        AND BKPF.MANDT = RSEG.MANDT
		AND SUBSTRING(BKPF.AWKEY,1,14) = RSEG.BELNR || CAST(RSEG.GJAHR AS VARCHAR(4))
     INNER JOIN _CEL_P2P_CASES AS CASES ON 1=1
        AND RSEG.MANDT = CASES.MANDT
        AND RSEG.EBELN = CASES.EBELN
        AND RSEG.EBELP = CASES.EBELP
WHERE BSEG.KOART = 'K';
