
INSERT INTO _CEL_P2P_ACTIVITIES(
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"_CELONIS_CHANGE_DATE")
SELECT DISTINCT 
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,'Sende Bestellung' AS "ACTIVITY_DE"
	,'Send Order' AS "ACTIVITY_EN"
	,CAST(WF_LOG.DATUM AS DATE) + CAST(WF_LOG.ZEIT AS TIME) AS "EVENTTIME"
	,541 AS "_SORTING"
	,WF_LOG.USER_NAME AS "USER_NAME"
	,NOW() AS "_CELONIS_CHANGE_DATE"
FROM

	TMP_P2P_EKKO_EKPO AS E 
	JOIN "Z0MM_WF_LOGGING" AS WF_LOG ON 1=1
        AND WF_LOG.BELEGNUMMER = E.EBELN
        AND WF_LOG.MANDT = E.MANDT
        WHERE WF_LOG.MESSAGE_TYPE = 'Mail'

