/*DESCRIPTION:
1. Transformation Description:
This transformation creates an activity with the following name: Create Contract

















2. Required Tables:
CDHDR
CDPOS
EKKO
EKPO
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
CDHDR.CHANGENR
CDHDR.MANDANT
CDHDR.UDATE
CDHDR.USERNAME
CDHDR.UTIME
CDPOS.CHANGENR
CDPOS.CHNGIND
CDPOS.FNAME
CDPOS.MANDANT
CDPOS.TABKEY
CDPOS.TABNAME
EKKO.AEDAT
EKKO.BSTYP
EKKO.EBELN
EKKO.MANDT
EKPO.EBELN
EKPO.EBELP
EKPO.MANDT
TMP_P2P_EKKO_EKPO.EBELN
TMP_P2P_EKKO_EKPO.EBELP
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
CDHDR.UDATE
CDHDR.UTIME
EKKO.AEDAT

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/
INSERT INTO _CEL_P2P_ACTIVITIES (
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
    ,"_ACTIVITY_KEY")

SELECT DISTINCT 
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,'Vertrag erstellt' AS ACTIVITY_DE
	,'Create Contract' AS ACTIVTIY_EN
	,CASE
        WHEN coalesce(CDHDR_HEAD.UDATE,'')<> '' THEN CAST(CDHDR_HEAD.UDATE AS DATE) + CAST(CDHDR_HEAD.UTIME AS TIME)
        ELSE CAST(EKKO_CONTRACT.AEDAT AS DATE) + CAST('00:00:01' AS TIME)
    END AS "EVENTTIME"
    ,100 AS "_SORTING"
    ,COALESCE(CDHDR_HEAD.USERNAME, E.ERNAM) As "USER_NAME"
    ,USR02_HEAD.USTYP AS "USER_TYPE"
    , EKKO_CONTRACT.MANDT || EKKO_CONTRACT.EBELN AS "_ACTIVITY_KEY"
FROM TMP_P2P_EKKO_EKPO AS E
INNER JOIN EKPO AS EKPO_CONTRACT ON 1=1
	AND E.MANDT = EKPO_CONTRACT.MANDT 
	AND E.KONNR = EKPO_CONTRACT.EBELN
	AND E.KTPNR = EKPO_CONTRACT.EBELP
INNER JOIN EKKO AS EKKO_CONTRACT ON 1=1
	AND EKPO_CONTRACT.MANDT = EKKO_CONTRACT.MANDT 
	AND EKPO_CONTRACT.EBELN = EKKO_CONTRACT.EBELN
    AND EKKO_CONTRACT.BSTYP='K'
LEFT JOIN CDPOS AS CDPOS_HEAD ON 1=1
	AND CDPOS_HEAD.TABKEY = EKKO_CONTRACT.MANDT || EKKO_CONTRACT.EBELN 
	AND CDPOS_HEAD.TABNAME = 'EKKO' 
	AND CDPOS_HEAD.CHNGIND = 'I' 
	AND CDPOS_HEAD.FNAME = 'KEY'
LEFT JOIN CDHDR AS CDHDR_HEAD ON 1=1
	AND CDPOS_HEAD.MANDANT = CDHDR_HEAD.MANDANT
	AND CDPOS_HEAD.CHANGENR = CDHDR_HEAD.CHANGENR
LEFT JOIN USR02 AS USR02_HEAD ON 1=1
	AND CDHDR_HEAD.MANDANT = USR02_HEAD.MANDT
	AND CDHDR_HEAD.USERNAME = USR02_HEAD.BNAME;
