/*DESCRIPTION:
1. Transformation Description:
This transformation creates the following activities: Decrease Contract Net Price, Increase Contract Target Quantity, Decrease Contract Target Value, Increase Contract Net Price, Decrease Effective Contract Item Value, Increase Contract Target Value, Decrease Contract Target Quantity, Increase Effective Contract Item Value



2. Required Tables:
CDHDR
CDPOS
EKPO
T001
TCURF_CC
TCURR_CC
TCURX
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
CDHDR.CHANGENR
CDHDR.MANDANT
CDHDR.TCODE
CDHDR.UDATE
CDHDR.USERNAME
CDHDR.UTIME
CDPOS.CHANGENR
CDPOS.FNAME
CDPOS.MANDANT
CDPOS.OBJECTID
CDPOS.TABKEY
CDPOS.TABNAME
CDPOS.VALUE_NEW
CDPOS.VALUE_OLD
EKPO.AEDAT
EKPO.BSTYP
EKPO.BUKRS
EKPO.EBELN
EKPO.EBELP
EKPO.MANDT
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
CDHDR.UDATE
CDHDR.UTIME

5. Parameters used in where clause:
None

6. Parameters used in joins:
exchangeRateType
currency
*/
INSERT INTO _CEL_P2P_ACTIVITIES (
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
	,"CHANGED_TABLE"
	,"CHANGED_FIELD"
	,"CHANGED_FROM"
	,"CHANGED_TO"
	,"CHANGED_FROM_FLOAT"
	,"CHANGED_TO_FLOAT"
	,"CHANGE_NUMBER"
	,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
	 E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
   -- ,E.KONNR AS "KONNR"
  --  ,E.KTPNR AS "KTPNR"
	,CASE
        WHEN CDPOS.FNAME = 'KTMNG' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Erhöhe Vertrags Zielmenge'
        WHEN CDPOS.FNAME = 'KTMNG' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Senke Vertrags Zielmenge'
        WHEN CDPOS.FNAME = 'ZWERT' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Erhöhe Vertrags Zielwert'
        WHEN CDPOS.FNAME = 'ZWERT' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Senke Vertrags Zielwert'
        WHEN CDPOS.FNAME = 'NETPR' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Erhöhe Vertrags Preis'
        WHEN CDPOS.FNAME = 'NETPR' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Senke Vertrags Preis'
        WHEN CDPOS.FNAME = 'EFFWR' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Erhöhe effektiven Vertrags Bestellwert'
        WHEN CDPOS.FNAME = 'EFFWR' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Senke effektiven Vertrags Bestellwert'
	END AS "ACTIVITY_DE"
	,CASE 
        WHEN CDPOS.FNAME = 'KTMNG' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Increase Contract Target Quantity'
        WHEN CDPOS.FNAME = 'KTMNG' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Decrease Contract Target Quantity'
        WHEN CDPOS.FNAME = 'ZWERT' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Increase Contract Target Value'
        WHEN CDPOS.FNAME = 'ZWERT' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Decrease Contract Target Value'
        WHEN CDPOS.FNAME = 'NETPR' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Increase Contract Net Price'
        WHEN CDPOS.FNAME = 'NETPR' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Decrease Contract Net Price'
        WHEN CDPOS.FNAME = 'EFFWR' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 'Increase Effective Contract Item Value'
        WHEN CDPOS.FNAME = 'EFFWR' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 'Decrease Effective Contract Item Value'
	END AS "ACTIVITY_EN"
	,CAST(CAST(CDHDR.UDATE AS DATE) || ' ' || CAST(CDHDR.UTIME AS TIME) AS DATETIME) AS "EVENTTIME"
	,CASE 
        WHEN CDPOS.FNAME = 'KTMNG' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 1110
        WHEN CDPOS.FNAME = 'KTMNG' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 1120
        WHEN CDPOS.FNAME = 'ZWERT' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 1130
        WHEN CDPOS.FNAME = 'ZWERT' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 1140
        WHEN CDPOS.FNAME = 'NETPR' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 1150
        WHEN CDPOS.FNAME = 'NETPR' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 1160
        WHEN CDPOS.FNAME = 'EFFWR' AND CDPOS.VALUE_NEW > CDPOS.VALUE_OLD THEN 1170
        WHEN CDPOS.FNAME = 'EFFWR' AND CDPOS.VALUE_NEW < CDPOS.VALUE_OLD THEN 1180
	END AS "_SORTING"
	,CDHDR.USERNAME AS "USER_NAME"
	,USR02.USTYP AS "USER_TYPE"
	,CDPOS.TABNAME AS "CHANGED_TABLE"
	,CDPOS.FNAME AS "CHANGED_FIELD"
	,CDPOS.VALUE_OLD AS "CHANGED_FROM"
	,CDPOS.VALUE_NEW AS "CHANGED_TO"
	,CASE
		WHEN CDPOS.FNAME = 'NETPR' THEN
		(CASE 
			WHEN E.WAERS = '<%=currency%>' THEN CDPOS.VALUE_OLD*IFNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CDPOS.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CDPOS.VALUE_OLD*IFNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		END)
		ELSE CAST(NULL AS FLOAT)
	END AS "CHANGED_FROM_FLOAT"
	,CASE
		WHEN CDPOS.FNAME = 'NETPR' THEN
		(CASE 
			WHEN E.WAERS = '<%=currency%>' THEN CDPOS.VALUE_NEW*IFNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CDPOS.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CDPOS.VALUE_NEW*IFNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		END)
		ELSE CAST(NULL AS FLOAT)
	END AS "CHANGED_TO_FLOAT"
	,CDHDR.CHANGENR AS "CHANGE_NUMBER"
	,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY"
FROM
	CDPOS AS CDPOS
	INNER JOIN EKPO AS CONTRACTS ON 1=1
		AND CDPOS.OBJECTID = CONTRACTS.EBELN
		AND CDPOS.TABKEY = CONTRACTS.MANDT ||CONTRACTS.EBELN ||CONTRACTS.EBELP
		AND CDPOS.MANDANT = CONTRACTS.MANDT
	JOIN CDHDR AS CDHDR ON 1=1
		AND CDPOS.MANDANT = CDHDR.MANDANT
		AND CDPOS.CHANGENR = CDHDR.CHANGENR
    INNER JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
    	AND E.MANDT = CONTRACTS.MANDT 
        AND E.KONNR = CONTRACTS.EBELN
        AND E.KTPNR = CONTRACTS.EBELP
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND USR02.MANDT = CDHDR.MANDANT
		AND USR02.BNAME = CDHDR.USERNAME
	LEFT JOIN TCURR_CC AS TCURR_CC ON 1=1
		AND TCURR_CC.MANDT = E.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = E.WAERS
		AND TCURR_CC.KURST = '<%=exchangeRateType%>'
		AND cast(E.AEDAT as date) >= cast(TCURR_CC.VALID_START as date)
		AND cast(E.AEDAT as date) < cast(TCURR_CC.VALID_END as date)
	LEFT JOIN TCURF_CC AS TCURF_CC ON 1=1
		AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
		AND cast(CONTRACTS.AEDAT as date)  >= cast(TCURF_CC.VALID_START	as date)
		AND cast(CONTRACTS.AEDAT as date) < cast(TCURF_CC.VALID_END as date)
	LEFT JOIN T001 AS T001 ON 1=1
		AND CONTRACTS.MANDT = T001.MANDT
		AND CONTRACTS.BUKRS = T001.BUKRS
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		AND TCURR_CC.FCURR = TCURX.CURRKEY
WHERE 1=1
	AND CONTRACTS.BSTYP = 'K'
	AND CDPOS.TABNAME IN ('EKPO')
	AND CDPOS.FNAME IN ('NETPR', 'KTMNG', 'ZWERT', 'EFFWR');