/*DESCRIPTION:
View for Metadata in Reporting Layer
*/
DROP VIEW IF EXISTS "P2P_Z0MM_WF_LOGGING";
CREATE VIEW P2P_Z0MM_WF_LOGGING AS 
SELECT DISTINCT 
    WF_LOG.*
  FROM "Z0MM_WF_LOGGING" AS WF_LOG 
  WHERE WF_LOG.MESSAGE_TYPE = 'CHECKIN'

    