/*DESCRIPTION:
1. Transformation Description:
This transformation creates an activity with the following name: Clear Invoice

















2. Required Tables:
BKPF
RSEG
TMP_P2P_BKPF_BSEG
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
BKPF.BELNR
BKPF.BUKRS
BKPF.CPUDT
BKPF.CPUTM
BKPF.GJAHR
BKPF.MANDT
BKPF.TCODE
BKPF.USNAM
RSEG.BELNR
RSEG.EBELN
RSEG.EBELP
RSEG.GJAHR
RSEG.MANDT
TMP_P2P_BKPF_BSEG.AUGBL
TMP_P2P_BKPF_BSEG.AUGDT
TMP_P2P_BKPF_BSEG.AUGGJ
TMP_P2P_BKPF_BSEG.AWKEY
TMP_P2P_BKPF_BSEG.BUKRS
TMP_P2P_BKPF_BSEG.KOART
TMP_P2P_BKPF_BSEG.MANDT
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
BKPF.CPUDT
BKPF.CPUTM
TMP_P2P_BKPF_BSEG.AUGDT

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/
INSERT INTO _CEL_P2P_ACTIVITIES(
    "_CASE_KEY"
    ,"MANDT"
    ,"EBELN"
    ,"EBELP"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY" )
SELECT DISTINCT
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,'Gleiche Rechnung aus' AS "ACTIVITY_DE"
	,'Clear Invoice' AS "ACTIVITY_EN"
	,CASE 
  		WHEN CAST(BKPF_Z."CPUDT" AS DATE) = CAST(B."AUGDT" AS DATE)
  		THEN CAST(BKPF_Z."CPUDT" AS DATE) + CAST(BKPF_Z."CPUTM" as TIME)
  		ELSE CAST(B."AUGDT" AS DATE) + CAST('23:59:59' as TIME)
  	END AS "EVENTTIME"
	,2500 AS "_SORTING"
	,BKPF_Z.USNAM AS "USER_NAME"
	,USR02.USTYP AS "USER_TYPE"
	,BKPF_Z.TCODE AS "TRANSACTION_CODE"
    ,B."MANDT" || B."BUKRS" || B."BELNR" || B."GJAHR" AS "_ACTIVITY_KEY"
FROM 
	RSEG AS RSEG
	INNER JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
	    AND RSEG.MANDT = E.MANDT
	    AND RSEG.EBELN = E.EBELN
	    AND RSEG.EBELP = E.EBELP
	INNER JOIN TMP_P2P_BKPF_BSEG AS B ON 1=1
		AND B.MANDT = RSEG.MANDT
		AND SUBSTRING(B.AWKEY,1,14) = RSEG.BELNR || CAST(RSEG.GJAHR AS VARCHAR(4))
	LEFT JOIN BKPF AS BKPF_Z ON 1=1
		AND B.MANDT = BKPF_Z.MANDT
		AND B.BUKRS = BKPF_Z.BUKRS
		AND B.AUGBL = BKPF_Z.BELNR
		AND B.AUGGJ = BKPF_Z.GJAHR
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND BKPF_Z.MANDT = USR02.MANDT
		AND BKPF_Z.USNAM = USR02.BNAME
WHERE
	B.KOART = 'K' AND	
	coalesce(B.AUGBL,'') <> '' AND
	coalesce(BKPF_Z.CPUDT,'') <> ''
;

