/*DESCRIPTION:
1. Transformation Description:
This transformation creates the following activities: Release Purchase Order, Change Currency, Refuse Purchase Order, Change Vendor, Change Approval for Purchase Order

















2. Required Tables:
CDHDR
CDPOS
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
CDHDR.BLOCKPOINDICATORS
CDHDR.CHANGENR
CDHDR.MANDANT
CDHDR.RELEASEPOINDICATORS
CDHDR.TCODE
CDHDR.UDATE
CDHDR.USERNAME
CDHDR.UTIME
CDPOS.CHANGENR
CDPOS.FNAME
CDPOS.MANDANT
CDPOS.OBJECTID
CDPOS.TABKEY
CDPOS.TABNAME
CDPOS.VALUE_NEW
CDPOS.VALUE_OLD
TMP_P2P_EKKO_EKPO.EBELN
TMP_P2P_EKKO_EKPO.EBELP
TMP_P2P_EKKO_EKPO.MANDT
TMP_P2P_EKKO_EKPO.TABKEY_EKKO
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
CDHDR.UDATE
CDHDR.UTIME

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/
INSERT INTO _CEL_P2P_ACTIVITIES (
	"_CASE_KEY"
	,"MANDT"
	,"EBELN"
	,"EBELP"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
	,"CHANGED_TABLE"
	,"CHANGED_FIELD"
	,"CHANGED_FROM"
	,"CHANGED_TO"
	,"CHANGE_NUMBER"
	,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
	,CASE
		WHEN CDPOS.FNAME = 'LIFNR' THEN 'Ändere Lieferant' 
		WHEN CDPOS.FNAME = 'FRGKE' AND CDPOS.VALUE_NEW IN <%=releasePoIndicators%> THEN 'Gebe Bestellung frei'
		WHEN CDPOS.FNAME = 'FRGKE' AND CDPOS.VALUE_NEW IN <%=blockPoIndicators%> THEN 'Lehne Bestellung ab'
		WHEN CDPOS.FNAME = 'FRGKE' THEN 'Ändere Freigabe für Bestellung'
		WHEN CDPOS.FNAME = 'WAERS' THEN 'Ändere Währung'
        WHEN CDPOS.FNAME = 'ZTERM' THEN 'Ändere Zahlungsbedingungen'
	END AS "ACTIVITY_DE"
	,CASE 
	    WHEN CDPOS.FNAME = 'LIFNR' THEN 'Change Vendor'
		WHEN CDPOS.FNAME = 'FRGKE' AND CDPOS.VALUE_NEW IN <%=releasePoIndicators%> THEN 'Release Purchase Order' 
		WHEN CDPOS.FNAME = 'FRGKE' AND  CDPOS.VALUE_NEW IN <%=blockPoIndicators%> THEN 'Refuse Purchase Order'
		WHEN CDPOS.FNAME = 'FRGKE' THEN 'Change Approval for Purchase Order' 
		WHEN CDPOS.FNAME = 'WAERS' THEN 'Change Currency'
        WHEN CDPOS.FNAME = 'ZTERM' THEN 'Change Payment Terms'
	END AS "ACTIVITY_EN"
	,CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME) AS "EVENTTIME"
	,CASE 
	    WHEN CDPOS.FNAME = 'LIFNR' THEN 910
		WHEN CDPOS.FNAME = 'FRGKE' AND CDPOS.VALUE_NEW IN <%=releasePoIndicators%> THEN 920
		WHEN CDPOS.FNAME = 'FRGKE' AND  CDPOS.VALUE_NEW IN <%=blockPoIndicators%> THEN 930
		WHEN CDPOS.FNAME = 'FRGKE' THEN 940
		WHEN CDPOS.FNAME = 'WAERS' THEN 950
        WHEN CDPOS.FNAME = 'ZTERM' THEN 960
	END AS "_SORTING"
	,CDHDR.USERNAME AS "USER_NAME"
	,USR02.USTYP AS "USER_TYPE"
	,CDPOS.TABNAME AS "CHANGED_TABLE"
	,CDPOS.FNAME AS "CHANGED_FIELD"
	,CDPOS.VALUE_OLD AS "CHANGED_FROM"
	,CDPOS.VALUE_NEW AS "CHANGED_TO"
	,CDHDR.CHANGENR AS "CHANGE_NUMBER"
	,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY"
FROM
	CDPOS AS CDPOS
	INNER JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
		AND CDPOS.OBJECTID = E.EBELN
		AND CDPOS.TABKEY = E."TABKEY_EKKO"
		AND CDPOS.MANDANT = E.MANDT
	JOIN CDHDR AS CDHDR ON 1=1
	    AND CDPOS.MANDANT = CDHDR.MANDANT
	    AND CDPOS.CHANGENR = CDHDR.CHANGENR
	LEFT JOIN USR02 AS USR02 ON 1=1
	    AND USR02.MANDT = CDHDR.MANDANT
		AND USR02.BNAME = CDHDR.USERNAME
WHERE
	CDPOS.FNAME IN ('LIFNR', 'WAERS', 'FRGKE') AND
	CDPOS.TABNAME = 'EKKO';