/*DESCRIPTION:
1. Transformation Description:
This transformation creates a view with the following name: P2P_LFB1

















2. Required Tables:
EKKO
LFB1
_CEL_P2P_CASES

3. Required Columns:
EKKO.BUKRS
EKKO.EBELN
EKKO.LIFNR
EKKO.MANDT
LFB1.*
LFB1.BUKRS
LFB1.LIFNR
LFB1.MANDT
_CEL_P2P_CASES.EBELN
_CEL_P2P_CASES.MANDT

4. Columns used for timestamp:
None

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/
DROP VIEW IF EXISTS P2P_LFB1;

CREATE VIEW P2P_LFB1 AS
SELECT DISTINCT 
	LFB1.*,
    CAST(LFB1.ERDAT AS DATE) AS TS_ERDAT,
    CAST(LFB1.ZINDT AS DATE) AS TS_ZINDT,
    CAST(LFB1.DATLZ AS DATE) AS TS_DATLZ,
    CAST(LFB1.QSZDT AS DATE) AS TS_QSZDT,
    CAST(LFB1.CERDT AS DATE) AS TS_CERDT,
    CAST(LFB1.UPDAT AS DATE) AS TS_UPDAT
FROM 
    LFB1
    INNER JOIN EKKO ON 1=1
		AND LFB1.MANDT = EKKO.MANDT
		AND LFB1.LIFNR = EKKO.LIFNR
		AND LFB1.BUKRS = EKKO.BUKRS
	INNER JOIN _CEL_P2P_CASES AS CASES ON 1=1
		AND EKKO.MANDT = CASES.MANDT
		AND EKKO.EBELN = CASES.EBELN
;