-- Add Activity: Cash Discount Due Date Passed, cbs 07.08.2020, Josef Rieger

INSERT INTO _CEL_P2P_ACTIVITIES(
    "_CASE_KEY"
    ,"MANDT"
    ,"EBELN"
    ,"EBELP"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
  )
 SELECT DISTINCT
	E._CASE_KEY AS "_CASE_KEY"
	,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
    ,'Erreiche Skontofrist' AS "ACTIVITY_DE"
	,'Cash Discount Due Date passed' AS "ACTIVITY_EN"
		,CAST((cast(B."ZFBDT"as date) + B."ZBD1T" * INTERVAL '1 day') AS DATE) + CAST('23:59:59' AS TIME) AS "EVENTTIME"
    ,2600 AS "_SORTING"
FROM 
	RSEG AS RSEG
	INNER JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
	    AND RSEG.MANDT = E.MANDT
	    AND RSEG.EBELN = E.EBELN
	    AND RSEG.EBELP = E.EBELP
	INNER JOIN TMP_P2P_BKPF_BSEG AS B ON 1=1
		AND B.MANDT = RSEG.MANDT
		AND SUBSTRING(B.AWKEY,1,14) = RSEG.BELNR || CAST(RSEG.GJAHR AS VARCHAR(4))
WHERE 1=1
	AND B."ZBD1P" > 0;
